from datetime import datetime
from server.models import Przedmiot, Opinia

SEED_PRZEDMIOTY = [
    Przedmiot(
        id="1",
        nazwa="Analiza Funkcjonalna",
        kod="1120-MA001-ISP-0524",
        ects=5,
        prowadzacy="dr hab. Marek Kowalski",
    ),
    Przedmiot(
        id="2",
        nazwa="Uczenie Maszynowe",
        kod="1120-IN002-ISP-0524",
        ects=6,
        prowadzacy="prof. dr hab. Anna Nowak",
    ),
    Przedmiot(
        id="3",
        nazwa="Kryptografia",
        kod="1120-IN003-ISP-0524",
        ects=5,
        prowadzacy="dr Tomasz Wiśniewski",
    ),
    Przedmiot(
        id="4",
        nazwa="Teoria Gier",
        kod="1120-MA004-ISP-0524",
        ects=6,
        prowadzacy="dr Piotr Zając",
    ),
    Przedmiot(
        id="5",
        nazwa="Programowanie Funkcyjne",
        kod="1120-IN005-ISP-0524",
        ects=4,
        prowadzacy="dr Karolina Maj",
    ),
    Przedmiot(
        id="6",
        nazwa="Topologia",
        kod="1120-MA006-ISP-0524",
        ects=5,
        prowadzacy="prof. dr hab. Jan Lis",
    ),
]


def get_seed_opinie():
    now = datetime.now()
    return [
        Opinia(
            id="o1",
            identyfikator_autora="auth_mock1",
            przedmiot_id="1",
            ocena=5,
            trudnosc=2,
            tresc_oryginalna="Świetny wykład, doktor tłumaczy bardzo przystępnie. Materiał trudny, ale dobrze prowadzony.",
            tresc_publiczna="Świetny wykład, doktor tłumaczy bardzo przystępnie. Materiał trudny, ale dobrze prowadzony.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o2",
            identyfikator_autora="auth_mock2",
            przedmiot_id="1",
            ocena=4,
            trudnosc=3,
            tresc_oryginalna="Dobre ćwiczenia, choć zaliczenie jest wymagające. Warto chodzić na wszystkie zajęcia.",
            tresc_publiczna="Dobre ćwiczenia, choć zaliczenie jest wymagające. Warto chodzić na wszystkie zajęcia.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o3",
            identyfikator_autora="auth_mock3",
            przedmiot_id="1",
            ocena=4,
            trudnosc=2,
            tresc_oryginalna="Interesujący przedmiot, ale sporo materiału do samodzielnego opanowania.",
            tresc_publiczna="Interesujący przedmiot, ale sporo materiału do samodzielnego opanowania.",
            status="zmieniona_i_opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o4",
            identyfikator_autora="auth_mock4",
            przedmiot_id="2",
            ocena=5,
            trudnosc=2,
            tresc_oryginalna="Najlepszy przedmiot na kierunku. Pani profesor jest niesamowita, projekt końcowy naprawdę uczy.",
            tresc_publiczna="Najlepszy przedmiot na kierunku. Pani profesor jest niesamowita, projekt końcowy naprawdę uczy.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o5",
            identyfikator_autora="auth_mock5",
            przedmiot_id="2",
            ocena=5,
            trudnosc=2,
            tresc_oryginalna="Bardzo praktyczny kurs. Po tym przedmiocie można spokojnie aplikować na staże z ML.",
            tresc_publiczna="Bardzo praktyczny kurs. Po tym przedmiocie można spokojnie aplikować na staże z ML.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o6",
            identyfikator_autora="auth_mock6",
            przedmiot_id="2",
            ocena=4,
            trudnosc=3,
            tresc_oryginalna="Dobry balans teorii i praktyki. Praca domowa czasochłonna, ale wartościowa.",
            tresc_publiczna="Dobry balans teorii i praktyki. Praca domowa czasochłonna, ale wartościowa.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o7",
            identyfikator_autora="auth_mock7",
            przedmiot_id="3",
            ocena=5,
            trudnosc=3,
            tresc_oryginalna="Fascynujący przedmiot. Dr Wiśniewski ma pasję do kryptografii, która się udziela.",
            tresc_publiczna="Fascynujący przedmiot. Dr Wiśniewski ma pasję do kryptografii, która się udziela.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o8",
            identyfikator_autora="auth_mock8",
            przedmiot_id="3",
            ocena=4,
            trudnosc=2,
            tresc_oryginalna="Matematyka jest wymagająca, ale dobrze wytłumaczona. Zadania laboratoryjne ciekawe.",
            tresc_publiczna="Matematyka jest wymagająca, ale dobrze wytłumaczona. Zadania laboratoryjne ciekawe.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o9",
            identyfikator_autora="auth_mock9",
            przedmiot_id="4",
            ocena=3,
            trudnosc=2,
            tresc_oryginalna="Ciekawy temat, ale prowadzenie mogłoby być lepsze. Zaliczenie trochę chaotyczne.",
            tresc_publiczna="Ciekawy temat, ale prowadzenie mogłoby być lepsze. Zaliczenie trochę chaotyczne.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o10",
            identyfikator_autora="auth_mock10",
            przedmiot_id="4",
            ocena=4,
            trudnosc=2,
            tresc_oryginalna="Unikalne spojrzenie na matematykę stosowaną. Warto wybrać jeśli interesuje Cię ekonomia.",
            tresc_publiczna="Unikalne spojrzenie na matematykę stosowaną. Warto wybrać jeśli interesuje Cię ekonomia.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o11",
            identyfikator_autora="auth_mock11",
            przedmiot_id="5",
            ocena=5,
            trudnosc=3,
            tresc_oryginalna="Haskell zmienił sposób w jaki myślę o programowaniu. Pani dr Maj tłumaczy monadę naprawdę klarownie.",
            tresc_publiczna="Haskell zmienił sposób w jaki myślę o programowaniu. Pani dr Maj tłumaczy monadę naprawdę klarownie.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o12",
            identyfikator_autora="auth_mock12",
            przedmiot_id="5",
            ocena=3,
            trudnosc=2,
            tresc_oryginalna="Interesujące, ale krzywa uczenia się bardzo stroma. Dla osób bez doświadczenia trudny start.",
            tresc_publiczna="Interesujące, ale krzywa uczenia się bardzo stroma. Dla osób bez doświadczenia trudny start.",
            status="opublikowana",
            data_opublikowania=now,
        ),
        Opinia(
            id="o13",
            identyfikator_autora="auth_mock13",
            przedmiot_id="6",
            ocena=3,
            trudnosc=3,
            tresc_oryginalna="Bardzo abstrakcyjny materiał. Wymaga dużej dojrzałości matematycznej.",
            tresc_publiczna="Bardzo abstrakcyjny materiał. Wymaga dużej dojrzałości matematycznej.",
            status="opublikowana",
            data_opublikowania=now,
        ),
    ]
